### PR TITLE
Reformatted MainViews File

### PR DESCRIPTION
**Pull request by saurabh69912162**
Please rename "constants.py" file name as per your convenience & do change in the mainviews.py

### CODE REVIEW

**Comment by kartik4949** [comment]
.idea files?

**Comment by saurabh69912162** [comment]
removed the folder

**Comment by kartik4949** [comment]
change constants.py to topics.py

**Comment by kartik4949** [comment]
@saurabh69912162  please rebase to main , i merged some new pr

**Comment by kartik4949** [comment]
@saurabh69912162 go for merge?

**Pull request merged**
